version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackmentor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      pgADMIN_DEFAULT_PASSWORD: admin
    ports:
        - "8080:80"
    depends_on:
        - postgres


volumes:
    pgdata: