spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stackmentor
    username: postgres
    password: postgres
    driver-class-name: com.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration