CREATE TABLE users (
    user_id UUID PRIMARY KEY,
    username VARCHAR(16) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(15) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    city VARCHAR(50),
    state VARCHAR(2),
    age INT,
    profile_picture_url VARCHAR(255),
    bio TEXT,
    mentor_status BOOLEAN DEFAULT FALSE,
    mentee_status BOOLEAN DEFAULT FALSE,
    job_title VARCHAR(100),
    years_of_experience INT,
    industry VARCHAR(100),
    skills TEXT,
    interests TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);